// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR52rdFDCBoNoKJuCjvEI7yPEGKNQWRkE',
    appId: '1:223188090153:web:5c3eed508f2ffe00c8cb38',
    messagingSenderId: '223188090153',
    projectId: 'cyclistguesser',
    authDomain: 'cyclistguesser.firebaseapp.com',
    storageBucket: 'cyclistguesser.firebasestorage.app',
    measurementId: 'G-BH6CCP0FVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2JqdyMRyqyGZEeuLrSQAU6DaPFZhXebc',
    appId: '1:223188090153:android:d567707ba3abbcdbc8cb38',
    messagingSenderId: '223188090153',
    projectId: 'cyclistguesser',
    storageBucket: 'cyclistguesser.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsuThqpkR5zlPoIbRbDTDrxFLxB43kiZg',
    appId: '1:223188090153:ios:126a74ae3cfe5f4ec8cb38',
    messagingSenderId: '223188090153',
    projectId: 'cyclistguesser',
    storageBucket: 'cyclistguesser.firebasestorage.app',
    iosBundleId: 'com.once.cyclistguesser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsuThqpkR5zlPoIbRbDTDrxFLxB43kiZg',
    appId: '1:223188090153:ios:126a74ae3cfe5f4ec8cb38',
    messagingSenderId: '223188090153',
    projectId: 'cyclistguesser',
    storageBucket: 'cyclistguesser.firebasestorage.app',
    iosBundleId: 'com.once.cyclistguesser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR52rdFDCBoNoKJuCjvEI7yPEGKNQWRkE',
    appId: '1:223188090153:web:f4b4687c33f202a5c8cb38',
    messagingSenderId: '223188090153',
    projectId: 'cyclistguesser',
    authDomain: 'cyclistguesser.firebaseapp.com',
    storageBucket: 'cyclistguesser.firebasestorage.app',
    measurementId: 'G-BMF66RWDJ0',
  );
}
